 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_gowchar_set/v_v_gowchar_set/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_gowchar_get/v_v_gowchar_get/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_SIZEOF_WCHAR_T/v_v_SIZEOF_WCHAR_T/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_get_feature_report/v_v_hid_get_feature_report/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_send_feature_report/v_v_hid_send_feature_report/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_exit/v_v_hid_exit/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_init/v_v_hid_init/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_error/v_v_hid_error/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_free_enumeration/v_v_hid_free_enumeration/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_open/v_v_hid_open/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_hid_open_path/v_v_v_hid_open_path/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_get_product_string/v_v_hid_get_product_string/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_get_manufacturer_string/v_v_hid_get_manufacturer_string/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_get_serial_number_string/v_v_hid_get_serial_number_string/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_get_indexed_string/v_v_hid_get_indexed_string/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_set_nonblocking/v_v_hid_set_nonblocking/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_write/v_v_hid_write/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_enumerate/v_v_hid_enumerate/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_close/v_v_hid_close/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_hid_read/v_v_hid_read/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_has_capability/v_v_libusb_has_capability/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_default_context/v_v_usbi_default_context/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_next_timeout/v_v_libusb_get_next_timeout/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_handle_events_timeout/v_v_v_libusb_handle_events_timeout/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_active_contexts_list/v_v_active_contexts_list/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_get_device_list/v_v_v_libusb_get_device_list/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_device_list/v_v_libusb_free_device_list/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_initCount/v_v_initCount/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_wait_for_event/v_v_libusb_wait_for_event/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_clear_event/v_v_usbi_clear_event/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_signal_event/v_v_usbi_signal_event/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_parent/v_v_libusb_get_parent/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_clear_halt/v_v_libusb_clear_halt/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_io_exit/v_v_usbi_io_exit/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_exit/v_v_libusb_exit/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_io_init/v_v_usbi_io_init/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_init/v_v_libusb_init/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_cond_timedwait/v_v_usbi_cond_timedwait/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_handle_disconnect/v_v_usbi_handle_disconnect/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_pollfds_handle_timeouts/v_v_libusb_pollfds_handle_timeouts/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_unlock_events/v_v_libusb_unlock_events/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_try_lock_events/v_v_libusb_try_lock_events/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_lock_events/v_v_libusb_lock_events/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_handle_events/v_v_libusb_handle_events/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_get_device_address/v_v_v_libusb_get_device_address/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_unlock_event_waiters/v_v_libusb_unlock_event_waiters/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_lock_event_waiters/v_v_libusb_lock_event_waiters/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_set_pollfd_notifiers/v_v_libusb_set_pollfd_notifiers/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_get_port_numbers/v_v_v_libusb_get_port_numbers/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_streams/v_v_libusb_free_streams/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_alloc_streams/v_v_libusb_alloc_streams/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_pollfds/v_v_libusb_get_pollfds/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_pollfds/v_v_libusb_free_pollfds/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_ss_usb_device_capability_descriptor/v_v_libusb_get_ss_usb_device_capability_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_ss_usb_device_capability_descriptor/v_v_libusb_free_ss_usb_device_capability_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_bos_descriptor/v_v_libusb_get_bos_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_bos_descriptor/v_v_libusb_free_bos_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_usb_2_0_extension_descriptor/v_v_libusb_get_usb_2_0_extension_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_usb_2_0_extension_descriptor/v_v_libusb_free_usb_2_0_extension_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_ss_endpoint_companion_descriptor/v_v_libusb_get_ss_endpoint_companion_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_ss_endpoint_companion_descriptor/v_v_libusb_free_ss_endpoint_companion_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_config_descriptor/v_v_libusb_get_config_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_active_config_descriptor/v_v_libusb_get_active_config_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_config_descriptor/v_v_libusb_free_config_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_parse_descriptor/v_v_usbi_parse_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_device_cache_descriptor/v_v_usbi_device_cache_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_get_device_descriptor/v_v_v_libusb_get_device_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_container_id_descriptor/v_v_libusb_get_container_id_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_container_id_descriptor/v_v_libusb_free_container_id_descriptor/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_strerror/v_v_libusb_strerror/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_attach_kernel_driver/v_v_libusb_attach_kernel_driver/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_set_auto_detach_kernel_driver/v_v_libusb_set_auto_detach_kernel_driver/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_detach_kernel_driver/v_v_libusb_detach_kernel_driver/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_interrupt_event_handler/v_v_libusb_interrupt_event_handler/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_interrupt_transfer/v_v_libusb_interrupt_transfer/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_submit_transfer/v_v_libusb_submit_transfer/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_control_transfer/v_v_libusb_control_transfer/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_cancel_transfer/v_v_libusb_cancel_transfer/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_bulk_transfer/v_v_libusb_bulk_transfer/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_free_transfer/v_v_libusb_free_transfer/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_alloc_transfer/v_v_libusb_alloc_transfer/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_port_number/v_v_libusb_get_port_number/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_bus_number/v_v_libusb_get_bus_number/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_signal_transfer_completion/v_v_usbi_signal_transfer_completion/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_handle_transfer_completion/v_v_usbi_handle_transfer_completion/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_set_configuration/v_v_libusb_set_configuration/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_configuration/v_v_libusb_get_configuration/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_handle_transfer_cancellation/v_v_usbi_handle_transfer_cancellation/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_hotplug_notification/v_v_usbi_hotplug_notification/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_version/v_v_libusb_get_version/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_open/v_v_libusb_open/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_event_handling_ok/v_v_libusb_event_handling_ok/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_active_contexts_lock/v_v_active_contexts_lock/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_hotplug_deregister_callback/v_v_libusb_hotplug_deregister_callback/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_hotplug_register_callback/v_v_libusb_hotplug_register_callback/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_string_descriptor_ascii/v_v_libusb_get_string_descriptor_ascii/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_port_path/v_v_libusb_get_port_path/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_hotplug_match/v_v_usbi_hotplug_match/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_set_debug/v_v_libusb_set_debug/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_set_interface_alt_setting/v_v_libusb_set_interface_alt_setting/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_max_packet_size/v_v_libusb_get_max_packet_size/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_max_iso_packet_size/v_v_libusb_get_max_iso_packet_size/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_kernel_driver_active/v_v_libusb_kernel_driver_active/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_event_handler_active/v_v_libusb_event_handler_active/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_get_config_index_by_value/v_v_usbi_get_config_index_by_value/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_get_config_descriptor_by_value/v_v_v_libusb_get_config_descriptor_by_value/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_close/v_v_libusb_close/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_pipe/v_v_usbi_pipe/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_error_name/v_v_libusb_error_name/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_setlocale/v_v_libusb_setlocale/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_dev_mem_free/v_v_libusb_dev_mem_free/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_reset_device/v_v_libusb_reset_device/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_get_device/v_v_libusb_get_device/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_disconnect_device/v_v_usbi_disconnect_device/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_connect_device/v_v_usbi_connect_device/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_unref_device/v_v_libusb_unref_device/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_ref_device/v_v_libusb_ref_device/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_sanitize_device/v_v_usbi_sanitize_device/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_alloc_device/v_v_usbi_alloc_device/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_claim_interface/v_v_libusb_claim_interface/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_release_interface/v_v_libusb_release_interface/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_discovered_devs_append/v_v_discovered_devs_append/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_backend/v_v_usbi_backend/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_get_tid/v_v_usbi_get_tid/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_open_device_with_vid_pid/v_v_v_libusb_open_device_with_vid_pid/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_get_device_by_session_id/v_v_usbi_get_device_by_session_id/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_transfer_set_stream_id/v_v_libusb_transfer_set_stream_id/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_libusb_transfer_get_stream_id/v_v_libusb_transfer_get_stream_id/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_remove_pollfd/v_v_usbi_remove_pollfd/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_usbi_add_pollfd/v_v_usbi_add_pollfd/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_v_libusb_handle_events_timeout_completed/v_v_v_v_libusb_handle_events_timeout_completed/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_handle_events_completed/v_v_v_libusb_handle_events_completed/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_handle_events_locked/v_v_v_libusb_handle_events_locked/g' {} +
 LC_CTYPE=C LANG=C find . -type f -exec sed -i '' -e 's/v_v_libusb_get_device_speed/v_v_v_libusb_get_device_speed/g' {} +
